### ISSUE TITLE
Issues Installing active_list

### ISSUE THREAD

**Issue by pcolazurdo** [ekylibre/active_list#3]
Hi, I've found this great gem by checking the ekylibre project and was trying to use this gem on my own project and found some issues with it. As I'm a newbie on rails I guess most issues are based on lack of experience but anyhow I guess this can be useful for others, if you think these tips are useful just feel free to add those into the readme file:

For me the initialization code on `ActiveList::Rails::Engine` just wasn't being called so I've had to:

create a `config/20-start.rb` and add:

```
require 'active_list'
::ActionController::Base.send(:include, ActiveList::Rails::Integration::ActionController)
::ActionView::Base.send(:include, ActiveList::Rails::Integration::ViewsHelper)
```

Additionally, some required files are not copied into the corresponding folders so I've had to copy them manually from the gem directory:
Copy these files into your `app/assets` folder:
to `./stylesheets` copy:

```
active_list.css.scss
active_list/background.scss
active_list/minimal.scss
active_list/theme.scss
```

to `./javascripts` copy:

```
active_list.jquery.js.coffee
```

Active_list is dependant on compass so you'll have to install this gems also:
`gem 'compass-rails'`

To make the sample code provided on github you'll have to modify your `routes.rb` as follows:

```
  resources :peoples do
    collection do
      get :list
    end
  end
```

hope it helps

**Comment by Aquaj** [comment]
Hi! 
Sorry we never got back to you before!
I'm not sure how exactly you ended up installing ActiveList into your project, but I'm glad you did end up making it work! 😄

Your installation method seems a bit unothodox so I'm afraid we won't add it to the README but I'm making a note that we do need more documentation.
Thanks for your interest and contribution!
